version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nft2023
      - POSTGRES_DB=postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_NAME=postgres
    depends_on:
      - postgres
    entrypoint:
      [ "/app/wait-for.sh", "postgres:5432", "--" ]
    command: [ "/app/server" ]

