// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	UserName      string  `json:"UserName"`
	Email         string  `json:"Email"`
	CreditBalance *string `json:"CreditBalance,omitempty"`
	DisplayName   *string `json:"DisplayName,omitempty"`
	WalletAddress *string `json:"WalletAddress,omitempty"`
}

type User struct {
	ID            string  `json:"ID"`
	UserName      string  `json:"UserName"`
	Email         string  `json:"Email"`
	CreditBalance string  `json:"CreditBalance"`
	DisplayName   *string `json:"DisplayName,omitempty"`
	WalletAddress *string `json:"WalletAddress,omitempty"`
	CreatedAt     *string `json:"CreatedAt,omitempty"`
	UpdatedAt     *string `json:"UpdatedAt,omitempty"`
}
